### ISSUE TITLE
Issue with get_endpoint_ca_information function call

### ISSUE THREAD

**Issue by Pansanel** [EGI-Foundation/cloud-info-provider#173] opened 2019-10-04 12:12 UTC
The function ssl_utils.get_endpoint_ca_information use three argument in providers/openstack.py:
https://github.com/EGI-Foundation/cloud-info-provider/blob/27e1877a35a82aa74be31184ffc1532ab6390119/cloud_info_provider/providers/openstack.py#L111

However, the function takes only two arguments in ssl_utils:
https://github.com/EGI-Foundation/cloud-info-provider/blob/27e1877a35a82aa74be31184ffc1532ab6390119/cloud_info_provider/providers/ssl_utils.py#L20

**Comment by enolfc** [comment] 2019-10-04 12:17
Thanks @Pansanel  for reporting the issue
It seems we miss some good testing here :(

**Comment by enolfc** [comment] 2019-10-04 12:19
Still 0.11.4 should be feature-wise the same for OpenStack, so no need to update from your side.

**Comment by kira2600** [comment] 2019-10-17 16:00
Hello.
Getting the same issue on 0.11.5:

```
ERROR:stevedore.extension:Could not load 'compute': get_endpoint_ca_information() takes at most 2 arguments (3 given)
ERROR:stevedore.extension:Could not load 'storage': get_endpoint_ca_information() takes at most 2 arguments (3 given)
ERROR:stevedore.extension:Could not load 'clouddomain': get_endpoint_ca_information() takes at most 2 arguments (3 given)
ERROR:stevedore.extension:Could not load 'headers': get_endpoint_ca_information() takes at most 2 arguments (3 given)
Traceback (most recent call last):
  File "/usr/bin/cloud-info-provider-service", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/cloud_info_provider/core.py", line 120, in main
    mgr.driver.format(opts, providers, auth_refresher)
  File "/usr/lib/python2.7/site-packages/cloud_info_provider/formatters/base.py", line 50, in format
    info = available_collectors[tpl].fetch()
KeyError: 'headers'
```

**Comment by enolfc** [comment] 2019-10-18 06:00
Hi @kira2600 

thanks for reporting about 0.11.4 too. I don't get this issue when running against your site with that same version for a few VOs I'm member of (but I'm getting a different one regarding the VM images #174). 

I'm trying to have them fixed asap.

**Comment by enolfc** [comment] 2019-10-18 08:48
I close this issue as #175 is merged. 

@kira2600, can we check via email/another issue the bug you are hitting with 0.11.4? I'm not able to reproduce

**Closed by enolfc** 2019-10-18 08:48 UTC
Labels: bug
