### ISSUE TITLE
Why is Synnefo not included in the list of supported providers ?

### ISSUE THREAD

**Issue by brucellino** [EGI-Foundation/cloud-info-provider#79] opened 2018-05-01 09:44 UTC
In the README (at least from bbf306c), there is mention of OpenStack and OpenNebula, but not Synnefo as a middleware provider. Is this a mistake or by design ?

**Comment by enolfc** [comment] 2018-05-01 19:37
The current code base does not support synnefo (not by design, simply because their changes were never merged). 

There was an attempt back in the day: https://github.com/enolfc/cloud-info-provider/tree/synnefo_support 

Any PR from synnefo will be welcomed.

**Closed by enolfc** 2018-05-01 19:37 UTC
Labels: :blue_book: docs, question
