### ISSUE TITLE
Improve community health.

### ISSUE THREAD

**Issue by brucellino** [EGI-Foundation/cloud-info-provider#76] opened 2018-04-30 12:59 UTC
This repository scores very low in the [Community Health](https://developer.github.com/v3/repos/community/) insight. In order to make it score better, and ensure a long-term healthy environment to community contributions, I propose to add the [Black Panter :fist_raised:](https://github.com/brucellino/black-panther) inspec compliance profile to the testing. 

This would include adding a few sections to the existing `.travis.yml` to test whether the things which characterise a healthy community are present.

**Comment by gwarf** [comment] 2018-04-30 13:15
Looks great, tested locally and it would be really helpful.
Looking forward for your PR.

![screen shot 2018-04-30 at 15 04 43](https://user-images.githubusercontent.com/451417/39428865-40b93bb0-4c89-11e8-89c0-334de3f0a73b.png)

**Comment by gwarf** [comment] 2018-05-02 08:12
Almost there, thanks @brucellino!

![screen shot 2018-05-02 at 10 10 55](https://user-images.githubusercontent.com/451417/39512421-3c2bd1c0-4df1-11e8-8bbd-2fee13f11ac0.png)

**Comment by gwarf** [comment] 2018-05-02 08:54
PR #77 states that copyright is owned by EGI Foundation, but it's not appropriate and should be discussed with the authors.

**Comment by gwarf** [comment] 2018-05-02 09:24
@alvarolopez highlighted in #77 that EGI Foundation should not claim the complete Copyright ownership unilaterally, let's discuss what is best to do.
- Removing copyright statement? (and relying informally on automatic copyright rules?)
- Having a generic/more inclusive copyright statement?
- Discussing copyright assignment?
- Mentioning EGI (but it's not a legal entity) instead of EGI Foundation?

**Comment by brucellino** [comment] 2018-05-02 11:48
I can live with that - but this is just stating the EGI owns the license. The license isn't copyright though... We definitely need consensus on who owns the license.

**Comment by enolfc** [comment] 2018-05-02 13:16
@brucellino is it really just for the license? By reading that I assume that EGI owns the code as there is no other copyright information in the repo. 

I would rather have a list of all the contributing institutions / individuals (I assume institutions should be fine here), we can easily get that from the repo.

**Comment by gwarf** [comment] 2018-05-02 14:37
@brucellino isn't it only the copyright owner that can decide what the license is?
And for me, the copyright mention in the license is to explicit who owns this copyright. But this was never really discussed. The fact is also that for some it will be their employer that will own the copyright of the work done, not the individual developer...

If the problem is making clear who are the contributors, we could add an AUTHORS file, would be easy to get it from the git history.

For the license, can't we just replace this by something similar to:
```
Copyright 2018, The authors
```

But more I look at Apache 2.0 the less I love it
OpenBSD doesn't even accept Apache 2.0: http://www.openbsd.org/policy.html

**Comment by brucellino** [comment] 2018-05-02 15:51
I couldn't care less really which license we choose, as long as there is one and the right people get credit for their work. Since this needs to have an _actual_ discussion, I propose the following : 

  1. We remove the license assertion from [the fashion police](https://github.com/EGI-Foundation/ansible-fashion-police), or at least accept more than one kind of license. But there must be a license.
  1. Close this issue and move it to the forum where we can continue the discussion in a civilised manner. 

To address the license itself in this repo, I think it should be up to the maintainer - @enolfc in this case.

We should probably come to some consensus of how to decide who owns the license - but I'm really glad we are hitting this issue, it's a sign of maturity :older_man: 

As soon as we get 3 :+1: I'll move it off to community.egi.eu

**Comment by enolfc** [comment] 2018-05-02 16:04
actually maintainer should be @gwarf :)

1. What does the fashion police needs to do with this? I'm a bit lost here

2. Ok with discussing this elsewhere

**Comment by brucellino** [comment] 2018-05-02 16:14
> What does the fashion police needs to do with this? I'm a bit lost here

Sorry, you're right - the License assertion is done in the [community health](https://github.com/brucellino-black-panther) profile. 

```
control 'I fought the law, but the law won' do
  impact 0.75
  title 'Wynona Earp  👮 ‍♀️'
  desc 'Ensure that there are rules in this wilderness'
  describe json('black-panther.json') do
    its(['files', 'code_of_conduct']) { should be }
    its(['files', 'license', 'key']) { should match '.*pache.*' }
    its(['files', 'license', 'spdx_id']) { should cmp 'Apache-2.0' }
  end
end
```

Maybe that is a wee bit too restrictive.

**Comment by gwarf** [comment] 2018-05-07 10:06
@alvarolopez could you please provide some feedback about this issue and/or about moving to discourse to discuss it?

**Comment by brucellino** [comment] 2018-05-07 10:08
Still waiting for 3 :+1:

**Comment by alvarolopez** [comment] 2018-05-09 10:37
> To address the license itself in this repo, I think it should be up to the maintainer - @enolfc in this 

Well, actually a lot of people have been maintaners: @enolfc, @spinto, @gwarf  and myself :-)

To be honest, personally I do not care, but somebody may raise this issue (now or in the future)

What I have seen in other projects is adding a header to each source file, where the individual copyrights are added when somebody edits that portion of code. Note that this can be also seen by some people as a visibility thing, but personally I do not care as long as there is a license.

**Comment by gwarf** [comment] 2018-06-25 13:37
All copyright files should also be updated. Couldn't we point to this repo or to some AUTHORS file instead of having to manually update multiple files?

**Comment by enolfc** [comment] 2018-06-27 08:20
We should automatically generate the AUTHORS file based on git commits already:
See https://docs.openstack.org/pbr/3.0.0/#authors-and-changelog

Copyright files should just point to those authors, no?

**Comment by gwarf** [comment] 2018-08-30 11:57
I propose to do something similar to what was done for the @EGI-Foundation/glite-info-update-endpoints repository: https://github.com/EGI-Foundation/glite-info-update-endpoints/pull/8

- So for the `AUTHORS` we could start feeling it using the git history, organize it, then configure pbr to not update the AUTHORS file (in order to allow to order/group people in the file as we need).
It's the way it's done for openstack/swift:
https://github.com/openstack/swift/blob/00373dad617db30bda3e8b722ab8518f59e0cb10/setup.cfg#L20-L22

- For the `COPYRIGHT` we could use a light version of the beginning of the rust one where each contributor keeps the ownership of the related copyright: https://github.com/rust-lang/rust/blob/master/COPYRIGHT

- And in the `LICENSE.txt` we put the ownership as `The authors`

Does it looks acceptable?

**Closed** 2018-09-26 14:16 UTC
Labels: bug, enhancement
